travis:
  secure:
    BINSTAR_TOKEN: eyqPo9aiu61ZriAgUeF7qYOiovY4+B7wj/geX913zGPgGquFvGw7+cIRHty2saBrl4BSPGfX7AO2EkeM9Km0JSnpS8MVWRkk7HvUQCGoo0MWX5BMSnx9Iki7xbliONq5oqkyna0DVaRZ5YGm9m4VaFPXngKVF6a8duYFccclCBfB3JEh2/5RQwj/g4itM1FGd5NUB16oqe32EK42PO9vS/UfcyCr23WMPD2Khl2gWg8zzbpwBVXM2Y8YItMWfVz3suPvJA1yvOFYB0WjnwkwHCKN2C8CFETWlQJAlZ3LMbrAA661M0Qk98YixwfZWBzMtF89gcwX0wckSQaSQydkcWD3Wt6rXqmSqaCgQjD+NNvYw2B4KjGMbBbutCxbNEgGcbEuWBZll5/4fxdXSnwdujRDGISMmp6u+F+3WX7cXepjJiXv6pQOwVwICJlAM2gKPO1V4ffonfBIH8izYVwZzUAn04hav6BQ9/6AbwOEpm4yIVPGIbmQ7oY7/iunjgM45mX8KXU0/yEmegdJ7Jf3lOqHFNLjUM1gVdQ8QfFTB0UUapWanhz0CPnSMfJFKOiEcst4iGIDF08Yd1VcuYzs+lRRGc8NPCjtzpSJYlDI3yvzAePRqhAJH5T/0ZNY/o7khwccKfQ34cm2GkwfEYtM2kno5JwSSgR7NOdYIEMYLH4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
