travis:
  secure:
    BINSTAR_TOKEN: KiDg4jaZKb6TcheCOBG76bzVPp4RouOkfe58+NreZ0uRMAK85zuV5It2wqDAYbWroJsVciAEmJWhx+gTECcMuTwUF4XiLDmfsvgu4CJ8rcK4eZwLwigcS9Ywelf9qvMd+b2ZyLg/aCD6Cf63yONhfas4dkph/yg3B+hDQVGejadrVqGpA7T+dCMWboIUXAJiL5nwhV3kReefh61L6iIFOpjNio32W/iE3f4HuDSCXMqszMA4Ih/g3WMCNtXMmT0A6m7SCOdPc41o8nMvVcAMmopS0jyKmV8Jp4K0dWDgw6HfEgDKxjG12+mXF8DxoNBwHwlj88zY5FhxiT3ZNoNbmvgOUNmyQQmK5OSe1VBqUm79I1uV8sbKUkksGsL3MmCW/5csmRh14co4i3PvqJwt5e/0gMC0jTcPIukP4bZv4zUof+0DIJ4symnMrFr3OuG+WjvsMejOtoT5WPtuwCrgN2ihvRXy9RC8NaSktT7rOh1gr04ZZ5nUcxcDsITaF4QhaiuYNvKKRsDNyk4zge2m7nXJAdZDEWMtJZxkvKpspffXOkZ1b6Ef65Ncfdw+QFqybgwyPv22TfCouoEjV6NuZqes3izbxgDn854w1r2WnbsA1hVcaz+9lQIUAKzlVZT8625Nr/heyokTNF37CwXQ5L7/3VWYMsBZGDZeF0c+QUw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
